# Some Dependencies
markdown: kramdown

# Permalinks
permalinks: pretty

# Setup
title: Tyler Epperson
url: https://edwardepperson.github.io

author: 
  name: 'Tyler Epperson'

sass:
  style: compact

# Custom
repository: github.com/edwardepperson/edwardepperson.github.io